<?php

declare(strict_types=1);

return [
    'module' => ['name' => 'Notifications'],
    'audit' => ['events' => ['published' => 'Notification published', 'updated' => 'Notification updated', 'activated' => 'Notification activated', 'deactivated' => 'Notification deactivated', 'deleted' => 'Notification deleted', 'restored' => 'Notification restored', 'display_reset' => 'Notification display reset']],
    'permissions' => ['view' => 'View notifications', 'publish' => 'Publish and edit notifications', 'activate' => 'Activate notifications', 'deactivate' => 'Deactivate notifications', 'delete' => 'Delete notifications', 'restore' => 'Restore notifications', 'reset_display' => 'Reset notification display'],
    'list' => ['title' => 'Notifications', 'description' => 'Published notifications for administration users.', 'loading' => 'Loading notifications…', 'empty' => 'No notifications found.', 'all' => 'All', 'active' => 'Active', 'inactive' => 'Inactive', 'deleted' => 'Deleted', 'search' => 'Search notifications'],
    'fields' => ['type' => 'Type', 'title' => 'Title', 'message' => 'Message', 'audience_type' => 'Recipients', 'roles' => 'Target roles', 'users' => 'Target users', 'audience' => 'Audience', 'author' => 'Author', 'status' => 'Status', 'created_at' => 'Published at', 'updated_at' => 'Updated at'],
    'audience_type' => ['roles' => 'By roles', 'users' => 'Specific users'],
    'audience_summary' => ['roles' => 'Roles: {audience}', 'users' => 'Users: {audience}'],
    'status' => ['active' => 'Active', 'inactive' => 'Inactive', 'deleted' => 'Deleted'],
    'types' => ['info' => 'Information', 'success' => 'Success', 'warning' => 'Warning', 'important' => 'Important'],
    'actions' => ['publish' => 'Publish notification', 'export' => 'Export CSV', 'activate' => 'Activate', 'activated' => 'Notification activated.', 'deactivate' => 'Deactivate', 'deactivated' => 'Notification deactivated.', 'delete' => 'Delete', 'deleted' => 'Notification deleted.', 'restore' => 'Restore', 'restored' => 'Notification restored.', 'restore_inactive' => 'Restore as inactive', 'reset_display' => 'Reset display', 'display_reset' => 'Notification display state has been reset.', 'bulk_deactivated' => 'Selected notifications were deactivated.', 'bulk_deleted' => 'Selected notifications were deleted.', 'bulk_activated' => 'Selected notifications were activated and their display state reset.', 'bulk_display_reset' => 'Selected notification display state was reset.', 'bulk_restored' => 'Selected notifications were restored as inactive.'],
    'confirm' => ['activate' => 'Activate this notification?', 'deactivate' => 'Deactivate this notification? It will disappear from recipient inboxes.', 'delete' => 'Delete this notification? It can be restored later.', 'restore' => 'Restore this notification with its original delivery state?', 'restore_inactive' => 'Restore selected notifications as inactive?', 'reset_display' => 'Reset the display state of this notification for all recipients?'],
    'editor' => ['create_title' => 'Publish notification', 'create_description' => 'Create an immediate notification for selected administration recipients.', 'modal_create_title' => 'Create notification', 'modal_create_description' => 'Fill in the notification content and choose recipients.', 'modal_edit_title' => 'Edit notification', 'modal_edit_description' => 'Update the notification content or recipients.', 'published' => 'Notification published.', 'updated' => 'Notification updated.', 'tabs' => ['basic' => 'Basic information'], 'roles_help' => 'When publishing, active users with the selected roles receive the notification.', 'users_help' => 'Choose active administration users.'],
    'validation' => ['type_required' => 'Choose a notification type.', 'type_invalid' => 'The notification type is invalid.', 'title_required' => 'Enter a title.', 'title_long' => 'The title is too long.', 'message_required' => 'Enter a message.', 'message_long' => 'The message is too long.', 'audience_type_required' => 'Choose a recipient method.', 'audience_type_invalid' => 'The recipient method is invalid.', 'audience_required' => 'Choose at least one recipient.', 'audience_exclusive' => 'Choose recipients either by roles or as specific users.', 'audience_forbidden' => 'You do not have permission to publish notifications for the selected recipients.', 'role_invalid' => 'One or more target roles is not active.', 'user_invalid' => 'One or more target users is not active.', 'role_forbidden' => 'You cannot publish to one or more selected roles.', 'user_forbidden' => 'You cannot publish to one or more selected users.', 'not_found' => 'Notification not found.', 'bulk_ids_invalid' => 'Select at least one valid notification.', 'deleted_cannot_change' => 'A deleted notification cannot be activated or deactivated.', 'deleted_cannot_edit' => 'A deleted notification cannot be edited.', 'deleted_cannot_reset_display' => 'A deleted notification display state cannot be reset.', 'lifecycle_changed' => 'The notification lifecycle changed. Refresh the list and try again.'],
];
