<?php

declare(strict_types=1);

return [
    'module' => ['name' => 'Oznámení'],
    'audit' => ['events' => ['published' => 'Oznámení publikováno', 'updated' => 'Oznámení upraveno', 'activated' => 'Oznámení aktivováno', 'deactivated' => 'Oznámení deaktivováno', 'deleted' => 'Oznámení smazáno', 'restored' => 'Oznámení obnoveno', 'display_reset' => 'Zobrazení oznámení resetováno']],
    'permissions' => ['view' => 'Zobrazit oznámení', 'publish' => 'Publikovat a upravovat oznámení', 'activate' => 'Aktivovat oznámení', 'deactivate' => 'Deaktivovat oznámení', 'delete' => 'Smazat oznámení', 'restore' => 'Obnovit oznámení', 'reset_display' => 'Resetovat zobrazení oznámení'],
    'list' => ['title' => 'Oznámení', 'description' => 'Publikovaná oznámení uživatelům administrace.', 'loading' => 'Načítání oznámení…', 'empty' => 'Nebyla nalezena žádná oznámení.', 'all' => 'Všechny', 'active' => 'Aktivní', 'inactive' => 'Neaktivní', 'deleted' => 'Smazané', 'search' => 'Hledat oznámení'],
    'fields' => ['type' => 'Typ', 'title' => 'Nadpis', 'message' => 'Text', 'audience_type' => 'Příjemci', 'roles' => 'Cílové role', 'users' => 'Cíloví uživatelé', 'audience' => 'Publikum', 'author' => 'Autor', 'status' => 'Stav', 'created_at' => 'Publikováno', 'updated_at' => 'Aktualizováno'],
    'audience_type' => ['roles' => 'Podle rolí', 'users' => 'Konkrétní uživatelé'],
    'audience_summary' => ['roles' => 'Role: {audience}', 'users' => 'Uživatelé: {audience}'],
    'status' => ['active' => 'Aktivní', 'inactive' => 'Neaktivní', 'deleted' => 'Smazané'],
    'types' => ['info' => 'Informace', 'success' => 'Úspěch', 'warning' => 'Upozornění', 'important' => 'Důležité'],
    'actions' => ['publish' => 'Publikovat oznámení', 'export' => 'Exportovat CSV', 'activate' => 'Aktivovat', 'activated' => 'Oznámení bylo aktivováno.', 'deactivate' => 'Deaktivovat', 'deactivated' => 'Oznámení bylo deaktivováno.', 'delete' => 'Smazat', 'deleted' => 'Oznámení bylo smazáno.', 'restore' => 'Obnovit', 'restored' => 'Oznámení bylo obnoveno.', 'restore_inactive' => 'Obnovit jako neaktivní', 'reset_display' => 'Resetovat zobrazení', 'display_reset' => 'Zobrazení oznámení bylo resetováno.', 'bulk_deactivated' => 'Vybraná oznámení byla deaktivována.', 'bulk_deleted' => 'Vybraná oznámení byla smazána.', 'bulk_activated' => 'Vybraná oznámení byla aktivována a jejich zobrazení resetováno.', 'bulk_display_reset' => 'Zobrazení vybraných oznámení bylo resetováno.', 'bulk_restored' => 'Vybraná oznámení byla obnovena jako neaktivní.'],
    'confirm' => ['activate' => 'Aktivovat toto oznámení?', 'deactivate' => 'Deaktivovat toto oznámení? Přestane se zobrazovat recipientům.', 'delete' => 'Smazat toto oznámení? Později jej lze obnovit.', 'restore' => 'Obnovit toto oznámení s původním stavem doručení?', 'restore_inactive' => 'Obnovit vybraná oznámení jako neaktivní?', 'reset_display' => 'Resetovat zobrazení tohoto oznámení pro všechny příjemce?'],
    'editor' => ['create_title' => 'Publikovat oznámení', 'create_description' => 'Vytvořte okamžité oznámení pro vybrané příjemce administrace.', 'modal_create_title' => 'Vytvořit oznámení', 'modal_create_description' => 'Vyplňte obsah oznámení a vyberte příjemce.', 'modal_edit_title' => 'Upravit oznámení', 'modal_edit_description' => 'Upravte obsah oznámení nebo jeho příjemce.', 'published' => 'Oznámení bylo publikováno.', 'updated' => 'Oznámení bylo upraveno.', 'tabs' => ['basic' => 'Základní údaje'], 'roles_help' => 'Při publikování dostanou oznámení aktivní uživatelé s vybranými rolemi.', 'users_help' => 'Vyberte aktivní uživatele administrace.'],
    'validation' => ['type_required' => 'Vyberte typ oznámení.', 'type_invalid' => 'Typ oznámení není platný.', 'title_required' => 'Zadejte nadpis.', 'title_long' => 'Nadpis je příliš dlouhý.', 'message_required' => 'Zadejte text.', 'message_long' => 'Text je příliš dlouhý.', 'audience_type_required' => 'Vyberte způsob příjemců.', 'audience_type_invalid' => 'Způsob příjemců není platný.', 'audience_required' => 'Vyberte alespoň jednoho příjemce.', 'audience_exclusive' => 'Zvolte příjemce buď podle rolí, nebo jako konkrétní uživatele.', 'audience_forbidden' => 'Nemáte oprávnění publikovat oznámení pro vybrané příjemce.', 'role_invalid' => 'Jedna nebo více cílových rolí není aktivní.', 'user_invalid' => 'Jeden nebo více cílových uživatelů není aktivní.', 'role_forbidden' => 'Nemáte oprávnění publikovat pro jednu nebo více vybraných rolí.', 'user_forbidden' => 'Nemáte oprávnění publikovat pro jednoho nebo více vybraných uživatelů.', 'not_found' => 'Oznámení nebylo nalezeno.', 'bulk_ids_invalid' => 'Vyberte alespoň jedno platné oznámení.', 'deleted_cannot_change' => 'Smazané oznámení nelze aktivovat ani deaktivovat.', 'deleted_cannot_edit' => 'Smazané oznámení nelze upravit.', 'deleted_cannot_reset_display' => 'Smazanému oznámení nelze resetovat zobrazení.', 'lifecycle_changed' => 'Stav oznámení se změnil. Obnovte seznam a zkuste to znovu.'],
];
