<?php

declare(strict_types=1);

return [
    'brand' => ['subtitle' => 'Redakční a administrační systém', 'poweredByLemonade' => 'Vytvořeno na Lemonade Framework'],
    'theme' => ['appearance' => 'Vzhled', 'system' => 'Systém', 'light' => 'Světlý', 'dark' => 'Tmavý'],
    'locale' => ['label' => 'Jazyk rozhraní', 'czech' => 'Čeština', 'english' => 'English'],
    'password' => ['show' => 'Zobrazit heslo', 'hide' => 'Skrýt heslo'],
    'install' => ['title' => 'Instalace Lemonade', 'update_title' => 'Aktualizace Lemonade', 'description' => 'Proveďte kontrolu prostředí a vytvořte první účet Root.', 'update_description' => 'Zkontrolujte prostředí a spusťte čekající aktualizace.', 'fields' => ['install_key' => 'Instalační klíč', 'email' => 'E-mail Root účtu', 'password' => 'Heslo Root účtu'], 'validation' => ['email_required' => 'Zadejte e-mail.', 'email_invalid' => 'Zadejte platný e-mail.', 'password_required' => 'Heslo je povinné.', 'password_min_length' => 'Heslo musí mít alespoň 12 znaků.'], 'errors' => ['invalid_key' => 'Instalační klíč není platný.'], 'preflight' => ['title' => 'Kontrola prostředí'], 'checks' => ['php' => 'PHP verze', 'extension.fileinfo' => 'PHP rozšíření fileinfo', 'extension.mbstring' => 'PHP rozšíření mbstring', 'extension.pdo' => 'PHP PDO extension', 'extension.pdo_mysql' => 'PHP PDO extension', 'database.configuration' => 'Konfigurace databáze', 'database.connection' => 'Připojení k databázi', 'storage' => 'Zapisovatelný storage', 'cache' => 'Zapisovatelná cache', 'vendor' => 'Composer vendor/autoload', 'assets.admin_css' => 'Admin CSS asset', 'assets.admin_js' => 'Admin JavaScript asset'], 'status' => ['success' => 'V pořádku', 'error' => 'Selhalo', 'skipped' => 'Přeskočeno'], 'steps' => ['title' => 'Výsledek', 'discovery' => 'Discovery modulů', 'database' => 'Core a databázové migrace', 'modules' => 'Migrace nainstalovaných modulů', 'permissions' => 'Synchronizace oprávnění', 'root' => 'Vytvoření Root účtu'], 'result' => ['success' => 'Operace byla úspěšně dokončena.', 'failure' => 'Operace selhala. Opravte uvedený problém a spusťte ji znovu.'], 'actions' => ['install' => 'Instalovat aplikaci', 'update' => 'Spustit aktualizaci', 'retry' => 'Opakovat']],
    'installErrors' => ['php' => 'Je vyžadována PHP 8.1 až 8.5.', 'extension' => ['fileinfo' => 'Je vyžadováno rozšíření PHP fileinfo.', 'mbstring' => 'Je vyžadováno rozšíření PHP mbstring.', 'pdo' => 'Je vyžadováno rozšíření PHP PDO.', 'pdo_mysql' => 'Je vyžadováno rozšíření PHP PDO MySQL.'], 'database' => 'Operace s databází selhala. Zkontrolujte konfiguraci a oprávnění.', 'database_host' => 'Host databáze není nakonfigurován.', 'database_port' => 'Port databáze není platný.', 'database_name' => 'Název databáze (DB_NAME) není nakonfigurován.', 'database_user' => 'Uživatel databáze (DB_USER) není nakonfigurován.', 'database_skipped' => 'Připojení nebylo ověřeno, protože konfigurace databáze není platná.', 'storage' => 'Adresář storage není zapisovatelný.', 'cache' => 'Adresář cache není zapisovatelný.', 'vendor' => 'Soubor vendor/autoload.php nebyl nalezen.', 'assets' => ['admin_css' => 'Admin CSS asset nebyl nalezen.', 'admin_js' => 'Admin JavaScript asset nebyl nalezen.'], 'preflight' => 'Nejprve opravte neúspěšné kontroly prostředí a stránku znovu načtěte.', 'credentials' => 'Údaje Root účtu jsou povinné.', 'catalog' => 'Katalog modulů není připraven.', 'step_order' => 'Instalační kroky musí proběhnout v daném pořadí.', 'step_invalid' => 'Instalační krok není platný.', 'operation_failed' => 'Operace selhala bez bližší diagnostiky.'],
    'installSteps' => ['environment' => 'Kontrola prostředí', 'pending' => 'Čeká', 'running' => 'Probíhá', 'success' => 'Hotovo', 'error' => 'Chyba', 'skipped' => 'Přeskočeno', 'prepare' => 'Připravit instalaci', 'refresh_catalog' => 'Obnovit katalog'],
    'installPresentation' => ['preflight_summary' => '{passed} z {total} kontrol prošlo.', 'progress' => 'Průběh instalace', 'progress_completed' => '{completed} z {total} kroků dokončeno', 'help' => ['install_key' => 'Klíč z environment konfigurace. Po ověření se neukládá.', 'email' => 'Bude použit pro první účet Root.', 'password' => 'Použijte alespoň 12 znaků.']],
];
