<?php

declare(strict_types=1);

return [
    'common' => [
        'save' => 'Save', 'save_changes' => 'Save changes', 'discard' => 'Discard', 'stay' => 'Stay', 'leave_without_saving' => 'Leave without saving', 'cancel' => 'Cancel', 'back' => 'Back', 'delete' => 'Delete', 'edit' => 'Edit', 'view' => 'View', 'duplicate' => 'Duplicate', 'add' => 'Add', 'close' => 'Close', 'search' => 'Search', 'apply' => 'Apply', 'actions' => 'Actions', 'preview' => 'Preview', 'name' => 'Name', 'category' => 'Category', 'author' => 'Author', 'date' => 'Date', 'status' => 'Status', 'views' => 'Views', 'language' => 'Language', 'confirm' => 'Confirm', 'continue' => 'Continue', 'hide' => 'Hide', 'activate' => 'Activate', 'pause' => 'Pause', 'download' => 'Download', 'poweredByLemonade' => 'Powered by Lemonade Framework',
    ],
    'brand' => ['subtitle' => 'Content Management System'],
    'administration' => ['navigation' => 'Administration'],
    'navigation' => ['dashboard' => 'Overview', 'content' => 'Content', 'commerce' => 'Commerce', 'users' => 'Users and access', 'system' => 'System'],
    'theme' => ['appearance' => 'Appearance', 'system' => 'System', 'light' => 'Light', 'dark' => 'Dark'],
    'confirm' => [
        'delete' => ['title' => 'Delete items?', 'message' => 'This action cannot be undone.'],
        'trash' => ['title' => 'Move items to trash?', 'message' => 'Items can be restored later.'],
    ],
    'message' => ['close' => 'Close', 'success' => 'The action was completed successfully.', 'error' => 'The action could not be completed.'],
    'file_upload' => ['select' => 'Select file', 'upload_change' => 'Upload / change', 'dropzone_title' => 'Drop files here or select a file', 'allowed_types' => 'Allowed types', 'max_size' => 'Max. {size} per file', 'file_too_large' => 'The file is too large. Maximum size is {size}.', 'extension_not_allowed' => 'This file type is not allowed.', 'remove_from_queue' => 'Remove from queue', 'remove' => 'Remove file', 'remove_confirm' => 'Are you sure you want to remove this file?', 'rename' => 'Rename', 'reorder' => 'Change order', 'rename_title' => 'Rename file', 'display_name' => 'Display name', 'display_name_required' => 'Enter a display name.', 'display_name_max_length' => 'Display name may contain at most 255 characters.', 'renamed' => 'The file name was saved.', 'retry' => 'Retry', 'failed' => 'The file could not be uploaded. Please try again.', 'gallery' => 'Gallery', 'attachments' => 'Attachments', 'gallery_help' => 'Upload images to the gallery.', 'attachments_help' => 'Upload documents.'],
    'file_variants' => ['title' => 'Generated variants', 'help' => 'Created automatically after upload.', 'datagrid' => 'Datagrid', 'datagrid_dimensions' => '32 × 32', 'thumbnail' => 'Thumbnail', 'thumbnail_dimensions' => '160 × 160'],
    'files' => ['audit' => ['events' => ['uploaded' => 'File uploaded', 'replaced' => 'File replaced', 'removed' => 'File removed', 'reordered' => 'Files reordered', 'renamed' => 'File renamed']]],
    'authorization' => ['forbidden' => 'You do not have permission to perform this action.'],
    'record' => ['not_found' => 'The record does not exist.'],
    'errors' => ['not_found' => ['breadcrumb' => 'Error', 'title' => 'Page not found', 'message' => 'This administration address is not valid.', 'card_title' => 'This page is not available', 'card_message' => 'Check the address, return to the overview, or continue using the menu on the left.', 'go_to_overview' => 'Go to overview', 'back' => 'Go back']],
    'editor' => ['unsaved_changes' => 'Unsaved changes', 'unsaved_changes_help' => 'Your changes have not been saved yet.', 'unsaved_changes_navigation' => 'You have unsaved changes', 'unsaved_changes_navigation_message' => 'Your unsaved changes will be lost when you leave this page.', 'record_locked' => 'This record is currently being edited by another user.', 'record_locked_by' => 'This record is currently being edited by {name}.', 'lock_lost' => 'The editor lock is no longer active. Reload the page.', 'record_conflict' => 'This record was changed by another user. Reload the current data and make your changes again.'],
    'sidebar' => ['mainNavigation' => 'Main navigation', 'sections' => 'Administration sections', 'collapse' => 'Collapse menu', 'collapseNavigation' => 'Collapse navigation', 'expandNavigation' => 'Expand navigation'],
    'topbar' => ['search' => 'Search administration...', 'help' => 'Help', 'viewWebsite' => 'View website', 'account' => 'User account'],
    'datagrid' => [
        'all' => 'All', 'more' => 'More', 'published' => 'Published', 'drafts' => 'Drafts', 'trash' => 'Trash', 'filters' => 'Filters', 'allCategories' => 'All categories', 'allAuthors' => 'All authors', 'allParents' => 'All parent pages', 'applyFilters' => 'Apply filters', 'clearFilters' => 'Clear filters', 'clearAllFilters' => 'Clear all', 'removeFilter' => 'Remove filter {filter}', 'refresh' => 'Refresh view', 'resetView' => 'Reset view', 'bulkActions' => 'Bulk actions', 'publish' => 'Publish', 'moveToTrash' => 'Move to trash', 'selectedCount' => 'Selected: {count}', 'clearSelection' => 'Clear selection', 'loading' => 'Loading items…', 'empty' => 'No items match the selected conditions.', 'error' => 'Unable to load items.', 'loadingData' => 'Loading data…', 'emptyTitle' => 'No data', 'emptyDescription' => 'There are no items here yet.', 'noResultsTitle' => 'No results', 'noResultsDescription' => 'Try adjusting your search or filters.', 'errorTitle' => 'Unable to load data', 'errorDescription' => 'The data could not be loaded. Please try again.', 'retry' => 'Retry', 'selectAll' => 'Select all', 'selectItem' => 'Select item', 'summary' => 'Showing {from}–{to} of {total} items', 'previous' => 'Previous', 'next' => 'Next', 'itemActions' => 'Item actions', 'untitled' => 'Untitled',
    ],
    'select' => ['loading' => 'Loading options…', 'error' => 'Unable to load options.', 'no_results' => 'No results found.', 'no_options' => 'No options available.', 'create' => 'Create “{name}”'],
    'status' => ['published' => 'Published', 'draft' => 'Draft', 'trash' => 'Trash', 'upcoming' => 'Upcoming', 'ongoing' => 'Ongoing', 'past' => 'Past', 'hidden' => 'Hidden', 'active' => 'Active', 'inactive' => 'Inactive', 'paused' => 'Paused'],
    'account' => ['profile' => 'My profile', 'settings' => 'Account settings', 'logout' => 'Log out', 'administrator' => 'Administrator', 'editor' => 'Editor', 'czech' => 'Čeština', 'english' => 'English'],
    'notifications' => ['title' => 'Notifications', 'description' => 'Overview of your personal notifications', 'loading' => 'Loading notifications…', 'error' => 'Unable to load notifications.', 'empty' => 'You have no new notifications.', 'markAllRead' => 'Mark all as read', 'markAllReadConfirm' => ['title' => 'Mark all as read?', 'message' => 'All notifications will be marked as read.', 'confirm' => 'Mark as read'], 'viewAll' => 'View all notifications', 'loadMore' => 'Load more', 'loadingMore' => 'Loading…', 'unread' => '{count} unread', 'actor' => ['system' => 'System', 'cron' => 'Scheduled task', 'migration' => 'Migration', 'unknownUser' => 'Unknown user']],
    'dashboard' => ['title' => 'Dashboard', 'module' => ['name' => 'Dashboard'], 'permissions' => ['manage' => 'Manage dashboard widgets'], 'widgets' => ['loading' => 'Loading widget…', 'error' => 'The widget could not be loaded.', 'retry' => 'Try again', 'refresh' => 'Refresh widget', 'empty' => 'This widget does not contain any data yet.', 'emptyDashboard' => 'You do not have any dashboard widgets yet.', 'customize' => 'Customize dashboard', 'add' => 'Add widget', 'added' => 'Added', 'done' => 'Done', 'remove' => 'Remove', 'moveUp' => 'Move up', 'moveDown' => 'Move down', 'drag' => 'Move widget', 'managed' => 'Managed by an administrator', 'noAvailable' => 'No widgets are available for your account.', 'size' => ['small' => 'Small', 'medium' => 'Medium', 'large' => 'Large', 'full' => 'Full width']], 'settings' => ['link' => 'Manage widgets', 'title' => 'Dashboard widget settings', 'description' => 'Assign managed widgets to roles or individual users.', 'targetType' => 'Target type', 'role' => 'Role', 'user' => 'User', 'selectTarget' => 'Select target', 'assigned' => 'Assigned widgets', 'available' => 'Available widgets', 'noAssigned' => 'No widgets are assigned to this target.', 'noAvailable' => 'No additional widgets are available.', 'noTargets' => 'You cannot manage any targets.', 'assignedBy' => 'Assigned by', 'inherited' => 'Inherited from role', 'direct' => 'Direct assignment', 'rootManaged' => 'Managed by superadmin', 'delegated' => 'Delegated assignment', 'unavailable' => 'Historical unavailable widget', 'add' => 'Add', 'remove' => 'Remove'], 'description' => 'Welcome back. Here is an overview of what matters most.', 'currentDateTime' => 'Current date and time', 'articles' => 'Articles', 'pages' => 'Pages', 'upcomingEvents' => 'Upcoming events', 'forms' => 'Forms', 'mediaFiles' => 'Media files', 'comparedToLastMonth' => 'compared with last month', 'traffic' => 'Website traffic', 'last30Days' => 'Last 30 days', 'topPages' => 'Most visited pages', 'page' => 'Page', 'trafficSources' => 'Traffic sources', 'views' => 'views', 'organicSearch' => 'Organic search', 'directTraffic' => 'Direct traffic', 'socialNetworks' => 'Social networks', 'referralTraffic' => 'Referral traffic', 'recentActivity' => 'Recent activity', 'viewAll' => 'View all'],
    'dashboard_audit' => ['widget_assigned_role' => 'Assigned widget “{widget}” to role “{target}”.', 'widget_assigned_user' => 'Assigned widget “{widget}” to user “{target}”.', 'widget_assigned_unknown_target' => 'Assigned widget “{widget}” to an unavailable target.', 'widget_unassigned_role' => 'Unassigned widget “{widget}” from role “{target}”.', 'widget_unassigned_user' => 'Unassigned widget “{widget}” from user “{target}”.', 'widget_unassigned_unknown_target' => 'Unassigned widget “{widget}” from an unavailable target.', 'preference_pinned' => 'Pinned widget “{widgetCode}”.', 'preference_unpinned' => 'Unpinned widget “{widgetCode}”.', 'preference_position_changed' => 'Changed position of widget “{widgetCode}”.', 'preference_size_changed' => 'Changed size of widget “{widgetCode}”.', 'preferences_reordered' => 'Reordered dashboard widgets.', 'unknown_widget' => 'Unavailable widget', 'unknown_role' => 'Unavailable role', 'unknown_user' => 'Unavailable user', 'unknown_target' => 'Unavailable target'],
];
