<?php

declare(strict_types=1);

use Lemonade\Admin\Icon\AdminIcon;
use Lemonade\Admin\Presentation\AdminFileUploadCollection;
use Lemonade\Framework\View\ViewHelpers;

/** @var ViewHelpers $helpers */
/** @var AdminFileUploadCollection $uploadCollection */
$isSingle = $uploadCollection->singleImage();
$isAvatar = $uploadCollection->presentation()->value === 'avatar';
$files = $uploadCollection->files();
$hasFile = $files !== [];
?>
<section class="lm-file-upload-collection<?= $isSingle ? ' lm-file-upload-collection--single lm-file-upload-collection--' . e($uploadCollection->presentation()->value) : '' ?>" data-lemonade-file-upload-collection data-lemonade-file-upload-single="<?= $isSingle ? 'true' : 'false' ?>" data-lemonade-file-upload-presentation="<?= e($uploadCollection->presentation()->value) ?>" data-lemonade-file-upload-start-url="<?= e($uploadCollection->startUrl()) ?>" data-lemonade-file-upload-append-url="<?= e($uploadCollection->appendUrlTemplate()) ?>" data-lemonade-file-upload-complete-url="<?= e($uploadCollection->completeUrlTemplate()) ?>" data-lemonade-file-upload-abort-url="<?= e($uploadCollection->abortUrlTemplate()) ?>" data-lemonade-file-upload-remove-url="<?= e($uploadCollection->removeUrlTemplate()) ?>" data-lemonade-file-upload-reorder-url="<?= e($uploadCollection->reorderUrl()) ?>" data-lemonade-file-upload-rename-modal-url="<?= e($uploadCollection->renameModalUrlTemplate()) ?>" data-lemonade-file-upload-kind="<?= e($uploadCollection->kind()) ?>" data-lemonade-file-upload-multiple="<?= $uploadCollection->multiple() ? 'true' : 'false' ?>" data-lemonade-file-upload-allowed-extensions="<?= e(implode(',', $uploadCollection->profile()->allowedExtensions())) ?>" data-lemonade-file-upload-max-bytes="<?= e((string) $uploadCollection->profile()->maxBytes()) ?>" data-lemonade-file-upload-max-size-label="<?= e($uploadCollection->profile()->maxSizeLabel()) ?>" data-lemonade-file-upload-file-too-large-label="<?= e($helpers->lang('admin.file_upload.file_too_large', ['size' => $uploadCollection->profile()->maxSizeLabel()])) ?>" data-lemonade-file-upload-extension-not-allowed-label="<?= e($helpers->lang('admin.file_upload.extension_not_allowed')) ?>" data-lemonade-file-upload-failed-label="<?= e($helpers->lang('admin.file_upload.failed')) ?>" data-lemonade-file-upload-discard-label="<?= e($helpers->lang('admin.file_upload.remove_from_queue')) ?>" data-lemonade-file-upload-remove-key="admin.file_upload.remove" data-lemonade-file-upload-remove-label="<?= e($helpers->lang('admin.file_upload.remove')) ?>" data-lemonade-file-upload-edit-label="<?= e($helpers->lang('admin.file_upload.edit')) ?>" data-lemonade-file-upload-reorder-label="<?= e($helpers->lang('admin.file_upload.reorder')) ?>" data-lemonade-file-upload-retry-label="<?= e($helpers->lang('admin.file_upload.retry')) ?>">
    <?php if ($isSingle): ?>
        <div class="lm-file-upload-tabs" role="tablist" aria-label="<?= e($helpers->lang('admin.common.preview')) ?>" data-lemonade-i18n-aria-label="admin.common.preview">
            <button class="lm-file-upload-tab<?= $hasFile ? ' is-active' : '' ?>" type="button" role="tab" aria-selected="<?= $hasFile ? 'true' : 'false' ?>" data-lemonade-file-upload-tab="preview" data-lemonade-i18n="admin.common.preview"><?= e($helpers->lang('admin.common.preview')) ?></button>
            <button class="lm-file-upload-tab<?= $hasFile ? '' : ' is-active' ?>" type="button" role="tab" aria-selected="<?= $hasFile ? 'false' : 'true' ?>" data-lemonade-file-upload-tab="upload" data-lemonade-i18n="admin.file_upload.upload_change"><?= e($helpers->lang('admin.file_upload.upload_change')) ?></button>
        </div>
        <div class="lm-file-upload-panel" data-lemonade-file-upload-panel="preview"<?= $hasFile ? '' : ' hidden' ?>>
            <div class="lm-file-upload-single-preview" data-lemonade-file-upload-single-preview>
                <?php if ($hasFile): $file = $files[0];
                    $displayName = (string) $file['display_name'] !== '' ? $file['display_name'] : $file['original_filename']; ?>
                    <article class="lm-file-upload-single lm-file-upload-single--<?= e($uploadCollection->presentation()->value) ?>" data-lemonade-file-upload-item data-lemonade-sortable-item="<?= e((string) $file['id']) ?>">
                        <?php if (!$isAvatar): ?><img class="lm-file-upload-single-image" src="<?= e((string) $file['preview_url']) ?>" alt="<?= e($uploadCollection->alt()) ?>"><?php endif; ?>
                        <div class="lm-file-upload-single-details"><strong><?= e((string) $displayName) ?></strong><small><?= e((string) $file['metadata']) ?></small></div>
                        <?php if ($uploadCollection->editable()): ?><span class="lm-file-upload-item-actions"><button class="btn btn-light btn-sm lm-file-upload-item-action" type="button" data-lemonade-modal-form-url="<?= e(str_replace('__upload_id__', (string) $file['id'], $uploadCollection->renameModalUrlTemplate())) ?>" data-lemonade-modal-size="medium" aria-label="<?= e($helpers->lang('admin.file_upload.edit')) ?>" title="<?= e($helpers->lang('admin.file_upload.edit')) ?>" data-lemonade-i18n-aria-label="admin.file_upload.edit" data-lemonade-i18n-title="admin.file_upload.edit"><i class="<?= e(AdminIcon::PencilSquare->cssClass()) ?>" aria-hidden="true"></i></button><button class="btn btn-light btn-sm lm-file-upload-item-action is-danger" type="button" data-lemonade-file-upload-remove aria-label="<?= e($helpers->lang('admin.file_upload.remove')) ?>" title="<?= e($helpers->lang('admin.file_upload.remove')) ?>" data-lemonade-i18n-aria-label="admin.file_upload.remove" data-lemonade-i18n-title="admin.file_upload.remove"><i class="<?= e(AdminIcon::Trash3->cssClass()) ?>" aria-hidden="true"></i></button></span><?php endif; ?>
                    </article>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
    <div class="lm-file-upload-panel" data-lemonade-file-upload-panel="upload"<?= $isSingle && $hasFile ? ' hidden' : '' ?>>
        <div class="lm-file-upload-dropzone"><span class="lm-file-upload-dropzone-icon" aria-hidden="true"><i class="<?= e(AdminIcon::Upload->cssClass()) ?>"></i></span><div class="lm-file-upload-dropzone-copy"><strong data-lemonade-i18n="admin.file_upload.dropzone_title"><?= e($helpers->lang('admin.file_upload.dropzone_title')) ?></strong><span class="lm-form-help" data-lemonade-i18n="<?= e($uploadCollection->helpKey()) ?>"><?= e($helpers->lang($uploadCollection->helpKey())) ?></span><label class="btn btn-light lm-file-upload-select"><span data-lemonade-i18n="admin.file_upload.select"><?= e($helpers->lang('admin.file_upload.select')) ?></span><input class="visually-hidden" type="file"<?= $uploadCollection->multiple() ? ' multiple' : '' ?> accept="<?= e($uploadCollection->profile()->accept()) ?>" data-lemonade-file-upload-input></label></div><div class="lm-file-upload-rules"><span class="lm-file-upload-rules-title" data-lemonade-i18n="admin.file_upload.allowed_types"><?= e($helpers->lang('admin.file_upload.allowed_types')) ?></span><div class="lm-file-upload-chips"><?php foreach ($uploadCollection->profile()->allowedExtensions() as $extension): ?><span class="lm-file-upload-chip"><?= e($extension) ?></span><?php endforeach; ?></div><small data-lemonade-i18n="admin.file_upload.max_size" data-lemonade-i18n-param-size="<?= e($uploadCollection->profile()->maxSizeLabel()) ?>"><?= e($helpers->lang('admin.file_upload.max_size', ['size' => $uploadCollection->profile()->maxSizeLabel()])) ?></small></div><span class="lm-form-help is-error" role="alert" hidden data-lemonade-file-upload-error></span></div>
        <div class="lm-file-upload-items" data-lemonade-file-upload-items<?= $uploadCollection->sortable() ? ' data-lemonade-sortable' : '' ?>>
            <?php if (!$isSingle): foreach ($files as $file): $displayName = (string) $file['display_name'] !== '' ? $file['display_name'] : $file['original_filename']; ?><article class="lm-file-upload-item" data-lemonade-file-upload-item data-lemonade-sortable-item="<?= e((string) $file['id']) ?>"><?php if (($file['preview_url'] ?? null) !== null): ?><img class="lm-file-upload-item-preview" src="<?= e((string) $file['preview_url']) ?>" alt=""><?php else: ?><span class="lm-file-upload-item-type" aria-hidden="true"><?= e(strtoupper((string) $file['extension'])) ?></span><?php endif; ?><span class="lm-file-upload-item-copy"><strong><?= e((string) $displayName) ?></strong><small><?= e((string) $file['metadata']) ?></small></span><?php if ($uploadCollection->sortable()): ?><button class="btn btn-light btn-sm lm-file-upload-item-action lm-file-upload-item-handle" type="button" data-lemonade-sortable-handle aria-label="<?= e($helpers->lang('admin.file_upload.reorder')) ?>" title="<?= e($helpers->lang('admin.file_upload.reorder')) ?>" data-lemonade-i18n-aria-label="admin.file_upload.reorder" data-lemonade-i18n-title="admin.file_upload.reorder"><i class="<?= e(AdminIcon::ArrowsMove->cssClass()) ?>" aria-hidden="true"></i></button><?php endif; ?><button class="btn btn-light btn-sm lm-file-upload-item-action" type="button" data-lemonade-modal-form-url="<?= e(str_replace('__upload_id__', (string) $file['id'], $uploadCollection->renameModalUrlTemplate())) ?>" data-lemonade-modal-size="medium" aria-label="<?= e($helpers->lang('admin.file_upload.edit')) ?>" title="<?= e($helpers->lang('admin.file_upload.edit')) ?>" data-lemonade-i18n-aria-label="admin.file_upload.edit" data-lemonade-i18n-title="admin.file_upload.edit"><i class="<?= e(AdminIcon::PencilSquare->cssClass()) ?>" aria-hidden="true"></i></button><button class="btn btn-light btn-sm lm-file-upload-item-action is-danger" type="button" data-lemonade-file-upload-remove aria-label="<?= e($helpers->lang('admin.file_upload.remove')) ?>" title="<?= e($helpers->lang('admin.file_upload.remove')) ?>" data-lemonade-i18n-aria-label="admin.file_upload.remove" data-lemonade-i18n-title="admin.file_upload.remove"><i class="<?= e(AdminIcon::Trash3->cssClass()) ?>" aria-hidden="true"></i></button></article><?php endforeach; endif; ?>
        </div>
    </div>
</section>
