<?php

declare(strict_types=1);

return [
    'common' => [
        'save' => 'Uložit', 'save_changes' => 'Uložit změny', 'discard' => 'Zahodit', 'stay' => 'Zůstat', 'leave_without_saving' => 'Odejít bez uložení', 'cancel' => 'Zrušit', 'back' => 'Zpět', 'delete' => 'Smazat', 'edit' => 'Upravit', 'view' => 'Zobrazit', 'duplicate' => 'Duplikovat', 'add' => 'Přidat', 'close' => 'Zavřít', 'search' => 'Hledat', 'apply' => 'Použít', 'actions' => 'Akce', 'preview' => 'Náhled', 'name' => 'Název', 'category' => 'Kategorie', 'author' => 'Autor', 'date' => 'Datum', 'status' => 'Stav', 'views' => 'Zobrazení', 'language' => 'Jazyk', 'confirm' => 'Potvrdit', 'continue' => 'Pokračovat', 'hide' => 'Skrýt', 'activate' => 'Aktivovat', 'pause' => 'Pozastavit', 'download' => 'Stáhnout', 'poweredByLemonade' => 'Vytvořeno na Lemonade Framework',
    ],
    'brand' => ['subtitle' => 'Redakční a administrační systém'],
    'administration' => ['navigation' => 'Správa'],
    'navigation' => ['dashboard' => 'Přehled', 'content' => 'Obsah', 'commerce' => 'Obchod', 'users' => 'Uživatelé a přístupy', 'system' => 'Systém'],
    'theme' => ['appearance' => 'Vzhled', 'system' => 'Systém', 'light' => 'Světlý', 'dark' => 'Tmavý'],
    'confirm' => [
        'delete' => ['title' => 'Smazat položky?', 'message' => 'Tuto akci nelze vrátit zpět.'],
        'trash' => ['title' => 'Přesunout položky do koše?', 'message' => 'Položky bude možné později obnovit.'],
    ],
    'message' => ['close' => 'Zavřít', 'success' => 'Akce byla úspěšně dokončena.', 'error' => 'Akci se nepodařilo dokončit.'],
    'file_upload' => ['select' => 'Vybrat soubor', 'upload_change' => 'Nahrát / změnit', 'dropzone_title' => 'Přetáhněte soubory sem nebo vyberte soubor', 'allowed_types' => 'Povolené typy', 'max_size' => 'Max. {size} na soubor', 'file_too_large' => 'Soubor je příliš velký. Maximální velikost je {size}.', 'extension_not_allowed' => 'Tento typ souboru není povolen.', 'remove_from_queue' => 'Odstranit z fronty', 'remove' => 'Odebrat soubor', 'remove_confirm' => 'Opravdu chcete soubor odstranit?', 'rename' => 'Přejmenovat', 'reorder' => 'Změnit pořadí', 'rename_title' => 'Přejmenovat', 'display_name' => 'Zobrazovaný název', 'display_name_required' => 'Zadejte zobrazovaný název.', 'display_name_max_length' => 'Zobrazovaný název může mít nejvýše 255 znaků.', 'renamed' => 'Název souboru byl uložen.', 'retry' => 'Opakovat', 'failed' => 'Soubor se nepodařilo nahrát. Zkuste to prosím znovu.', 'gallery' => 'Galerie', 'attachments' => 'Přílohy', 'gallery_help' => 'Nahrajte obrázky do galerie.', 'attachments_help' => 'Nahrajte dokumenty.'],
    'file_variants' => ['title' => 'Vygenerované varianty', 'help' => 'Vytvoří se automaticky po nahrání.', 'datagrid' => 'Datagrid', 'datagrid_dimensions' => '32 × 32', 'thumbnail' => 'Thumbnail', 'thumbnail_dimensions' => '160 × 160'],
    'files' => ['audit' => ['events' => ['uploaded' => 'Soubor nahrán', 'replaced' => 'Soubor nahrazen', 'removed' => 'Soubor odebrán', 'reordered' => 'Změněno pořadí souborů', 'renamed' => 'Soubor přejmenován']]],
    'authorization' => ['forbidden' => 'K této akci nemáte oprávnění.'],
    'record' => ['not_found' => 'Záznam neexistuje.'],
    'errors' => ['not_found' => ['breadcrumb' => 'Chyba', 'title' => 'Stránka nenalezena', 'message' => 'Tato adresa v administraci není platná.', 'card_title' => 'Stránka není dostupná', 'card_message' => 'Zkontrolujte adresu, vraťte se na přehled nebo pokračujte pomocí menu vlevo.', 'go_to_overview' => 'Přejít na přehled', 'back' => 'Zpět']],
    'editor' => ['unsaved_changes' => 'Neuložené změny', 'unsaved_changes_help' => 'Změny zatím nejsou uložené.', 'unsaved_changes_navigation' => 'Máte neuložené změny', 'unsaved_changes_navigation_message' => 'Při odchodu ze stránky budou neuložené změny ztraceny.', 'record_locked' => 'Záznam právě upravuje jiný uživatel.', 'record_locked_by' => 'Záznam právě upravuje {name}.', 'lock_lost' => 'Zámek editoru již není aktivní. Obnovte stránku.', 'record_conflict' => 'Záznam byl mezitím změněn jiným uživatelem. Načtěte aktuální data a proveďte změny znovu.'],
    'sidebar' => ['mainNavigation' => 'Hlavní navigace', 'sections' => 'Sekce administrace', 'collapse' => 'Sbalit menu', 'collapseNavigation' => 'Sbalit navigaci', 'expandNavigation' => 'Rozbalit navigaci'],
    'topbar' => ['search' => 'Hledat v administraci...', 'help' => 'Nápověda', 'viewWebsite' => 'Zobrazit web', 'account' => 'Uživatelský účet'],
    'datagrid' => [
        'all' => 'Vše', 'more' => 'Další', 'published' => 'Publikované', 'drafts' => 'Koncepty', 'trash' => 'V koši', 'filters' => 'Filtry', 'allCategories' => 'Všechny kategorie', 'allAuthors' => 'Všichni autoři', 'allParents' => 'Všechny nadřazené stránky', 'applyFilters' => 'Použít filtry', 'clearFilters' => 'Vymazat filtry', 'clearAllFilters' => 'Vymazat vše', 'removeFilter' => 'Odebrat filtr {filter}', 'refresh' => 'Obnovit zobrazení', 'resetView' => 'Resetovat zobrazení', 'bulkActions' => 'Hromadné akce', 'publish' => 'Publikovat', 'moveToTrash' => 'Přesunout do koše', 'selectedCount' => 'Vybrano: {count}', 'clearSelection' => 'Zrušit výběr', 'loading' => 'Načítání položek…', 'empty' => 'Pro zadané podmínky nebyly nalezeny žádné položky.', 'error' => 'Nepodařilo se načíst položky.', 'loadingData' => 'Načítání dat…', 'emptyTitle' => 'Žádná data', 'emptyDescription' => 'Zatím zde nejsou žádné položky.', 'noResultsTitle' => 'Žádné výsledky', 'noResultsDescription' => 'Zkuste upravit hledání nebo filtry.', 'errorTitle' => 'Nepodařilo se načíst data', 'errorDescription' => 'Data se nepodařilo načíst. Zkuste to znovu.', 'retry' => 'Opakovat', 'selectAll' => 'Vybrat vše', 'selectItem' => 'Vybrat položku', 'summary' => 'Zobrazeno {from}–{to} z {total} položek', 'previous' => 'Předchozí', 'next' => 'Další', 'itemActions' => 'Akce položky', 'untitled' => 'Bez názvu',
    ],
    'select' => ['loading' => 'Načítání možností…', 'error' => 'Možnosti se nepodařilo načíst.', 'no_results' => 'Nebyly nalezeny žádné výsledky.', 'no_options' => 'Nejsou k dispozici žádné možnosti.', 'create' => 'Vytvořit „{name}“'],
    'status' => ['published' => 'Publikováno', 'draft' => 'Koncept', 'trash' => 'V koši', 'upcoming' => 'Nadcházející', 'ongoing' => 'Probíhající', 'past' => 'Proběhlá', 'hidden' => 'Skryto', 'active' => 'Aktivní', 'inactive' => 'Neaktivní', 'paused' => 'Pozastaveno'],
    'account' => ['profile' => 'Můj profil', 'settings' => 'Nastavení účtu', 'logout' => 'Odhlásit se', 'administrator' => 'Administrátor', 'editor' => 'Editor', 'czech' => 'Čeština', 'english' => 'English'],
    'notifications' => ['title' => 'Oznámení', 'description' => 'Přehled vašich osobních oznámení', 'loading' => 'Načítání oznámení…', 'error' => 'Oznámení se nepodařilo načíst.', 'empty' => 'Nemáte žádná nová oznámení.', 'markAllRead' => 'Označit vše jako přečtené', 'markAllReadConfirm' => ['title' => 'Označit vše jako přečtené?', 'message' => 'Všechna oznámení budou označena jako přečtená.', 'confirm' => 'Označit jako přečtené'], 'viewAll' => 'Zobrazit všechna oznámení', 'loadMore' => 'Načíst další', 'loadingMore' => 'Načítání…', 'unread' => '{count} nepřečtené', 'actor' => ['system' => 'Systém', 'cron' => 'Plánovaná úloha', 'migration' => 'Migrace', 'unknownUser' => 'Neznámý uživatel']],
    'dashboard' => ['title' => 'Dashboard', 'module' => ['name' => 'Nástěnka'], 'permissions' => ['manage' => 'Spravovat dashboard widgety'], 'widgets' => ['loading' => 'Načítání widgetu…', 'error' => 'Widget se nepodařilo načíst.', 'retry' => 'Zkusit znovu', 'refresh' => 'Obnovit widget', 'empty' => 'Widget zatím neobsahuje žádná data.', 'emptyDashboard' => 'Na dashboardu zatím nemáte žádné widgety.', 'customize' => 'Přizpůsobit dashboard', 'add' => 'Přidat widget', 'added' => 'Přidáno', 'done' => 'Hotovo', 'remove' => 'Odebrat', 'moveUp' => 'Posunout nahoru', 'moveDown' => 'Posunout dolů', 'drag' => 'Přesunout widget', 'managed' => 'Spravuje administrátor', 'noAvailable' => 'Pro váš účet nejsou dostupné žádné widgety.', 'size' => ['small' => 'Malý', 'medium' => 'Střední', 'large' => 'Velký', 'full' => 'Celá šířka']], 'settings' => ['link' => 'Správa widgetů', 'title' => 'Správa dashboard widgetů', 'description' => 'Přidělte povinné widgety rolím nebo konkrétním uživatelům.', 'targetType' => 'Typ cíle', 'role' => 'Role', 'user' => 'Uživatel', 'selectTarget' => 'Vyberte cíl', 'assigned' => 'Přidělené widgety', 'available' => 'Dostupné widgety', 'noAssigned' => 'Pro tento cíl nejsou přidělené žádné widgety.', 'noAvailable' => 'Nejsou dostupné žádné další widgety.', 'noTargets' => 'Nemáte oprávnění spravovat žádný cíl.', 'assignedBy' => 'Přidělil', 'inherited' => 'Zděděno z role', 'direct' => 'Přímé přidělení', 'rootManaged' => 'Spravuje superadministrátor', 'delegated' => 'Delegované přidělení', 'unavailable' => 'Historicky nedostupný widget', 'add' => 'Přidat', 'remove' => 'Odebrat'], 'description' => 'Vítejte zpět. Tady je přehled toho nejdůležitějšího.', 'currentDateTime' => 'Aktuální datum a čas', 'articles' => 'Článků', 'pages' => 'Stránek', 'upcomingEvents' => 'Nadcházejících událostí', 'forms' => 'Formulářů', 'mediaFiles' => 'Mediálních souborů', 'comparedToLastMonth' => 'oproti minulému měsíci', 'traffic' => 'Návštěvnost webu', 'last30Days' => 'Posledních 30 dní', 'topPages' => 'Nejnavštěvovanější stránky', 'page' => 'Stránka', 'trafficSources' => 'Zdroje návštěvnosti', 'views' => 'zobrazení', 'organicSearch' => 'Organické vyhledávání', 'directTraffic' => 'Přímá návštěva', 'socialNetworks' => 'Sociální sítě', 'referralTraffic' => 'Odkaz z jiných webů', 'recentActivity' => 'Poslední aktivity', 'viewAll' => 'Zobrazit všechny'],
    'dashboard_audit' => ['widget_assigned_role' => 'Přiřazen widget „{widget}“ roli „{target}“.', 'widget_assigned_user' => 'Přiřazen widget „{widget}“ uživateli „{target}“.', 'widget_assigned_unknown_target' => 'Přiřazen widget „{widget}“ nedostupnému cíli.', 'widget_unassigned_role' => 'Odebrán widget „{widget}“ roli „{target}“.', 'widget_unassigned_user' => 'Odebrán widget „{widget}“ uživateli „{target}“.', 'widget_unassigned_unknown_target' => 'Odebrán widget „{widget}“ nedostupnému cíli.', 'preference_pinned' => 'Připnut widget „{widgetCode}“.', 'preference_unpinned' => 'Odebrán připnutý widget „{widgetCode}“.', 'preference_position_changed' => 'Změněna pozice widgetu „{widgetCode}“.', 'preference_size_changed' => 'Změněna velikost widgetu „{widgetCode}“.', 'preferences_reordered' => 'Změněno pořadí widgetů nástěnky.', 'unknown_widget' => 'Nedostupný widget', 'unknown_role' => 'Nedostupná role', 'unknown_user' => 'Nedostupný uživatel', 'unknown_target' => 'Nedostupný cíl'],
];
