<?php

declare(strict_types=1);

return [
    'brand' => ['subtitle' => 'Content Management System', 'poweredByLemonade' => 'Powered by Lemonade Framework'],
    'theme' => ['appearance' => 'Appearance', 'system' => 'System', 'light' => 'Light', 'dark' => 'Dark'],
    'locale' => ['label' => 'Interface language', 'czech' => 'Čeština', 'english' => 'English'],
    'password' => ['show' => 'Show password', 'hide' => 'Hide password'],
    'install' => ['title' => 'Lemonade installation', 'update_title' => 'Lemonade update', 'description' => 'Check the environment and create the first Root account.', 'update_description' => 'Check the environment and run pending updates.', 'fields' => ['install_key' => 'Installation key', 'email' => 'Root account email', 'password' => 'Root account password'], 'validation' => ['email_required' => 'Enter an email address.', 'email_invalid' => 'Enter a valid email address.', 'password_required' => 'Enter a password.', 'password_min_length' => 'The password must be at least 12 characters long.'], 'errors' => ['invalid_key' => 'The installation key is invalid.'], 'preflight' => ['title' => 'Environment preflight'], 'checks' => ['php' => 'PHP version', 'extension.fileinfo' => 'PHP fileinfo extension', 'extension.mbstring' => 'PHP mbstring extension', 'extension.pdo' => 'PHP PDO extension', 'extension.pdo_mysql' => 'PHP PDO MySQL extension', 'database.configuration' => 'Database configuration', 'database.connection' => 'Database connection', 'storage' => 'Writable storage', 'cache' => 'Writable cache', 'vendor' => 'Composer vendor/autoload', 'assets.admin_css' => 'Admin CSS asset', 'assets.admin_js' => 'Admin JavaScript asset'], 'status' => ['success' => 'OK', 'error' => 'Failed', 'skipped' => 'Skipped'], 'steps' => ['title' => 'Result', 'discovery' => 'Module discovery', 'database' => 'Core and database migrations', 'modules' => 'Installed module migrations', 'permissions' => 'Permission synchronization', 'root' => 'Root account creation'], 'result' => ['success' => 'The operation completed successfully.', 'failure' => 'The operation failed. Fix the reported problem and retry.'], 'actions' => ['install' => 'Install application', 'update' => 'Run update', 'retry' => 'Retry']],
    'installErrors' => ['php' => 'PHP 8.1 through 8.5 is required.', 'extension' => ['fileinfo' => 'The PHP fileinfo extension is required.', 'mbstring' => 'The PHP mbstring extension is required.', 'pdo' => 'The PHP PDO extension is required.', 'pdo_mysql' => 'The PHP PDO MySQL extension is required.'], 'database' => 'The database operation failed. Check the database configuration and permissions.', 'database_host' => 'The database host is not configured.', 'database_port' => 'The database port is invalid.', 'database_name' => 'The database name (DB_NAME) is not configured.', 'database_user' => 'The database user (DB_USER) is not configured.', 'database_skipped' => 'The connection was not checked because the database configuration is invalid.', 'storage' => 'The storage directory is not writable.', 'cache' => 'The cache directory is not writable.', 'vendor' => 'vendor/autoload.php was not found.', 'assets' => ['admin_css' => 'The Admin CSS asset was not found.', 'admin_js' => 'The Admin JavaScript asset was not found.'], 'preflight' => 'Fix the failed environment checks first, then reload this page.', 'credentials' => 'Root account credentials are required.', 'catalog' => 'The module catalog is not prepared.', 'step_order' => 'Installation steps must be executed in order.', 'step_invalid' => 'The installation step is invalid.', 'operation_failed' => 'The operation failed without a diagnostic message.'],
    'installSteps' => ['environment' => 'Environment check', 'pending' => 'Pending', 'running' => 'Running', 'success' => 'Complete', 'error' => 'Error', 'skipped' => 'Skipped', 'prepare' => 'Prepare installation', 'refresh_catalog' => 'Refresh catalog'],
    'installPresentation' => ['preflight_summary' => '{passed} of {total} checks passed.', 'progress' => 'Installation progress', 'progress_completed' => '{completed} of {total} steps complete', 'help' => ['install_key' => 'The key comes from environment configuration and is not stored after verification.', 'email' => 'This address will be used for the first Root account.', 'password' => 'Use at least 12 characters.']],
];
